name: ANCIR
markdown: kramdown

url: https://investigativecenters.org   # with the https protocol
enforce_ssl: investigativecenters.org   # without any protocol

encoding: utf-8

exclude:
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - test
  - tests
